### ISSUE TITLE
Brak możliwości połączenia z Bigshortbets app

### ISSUE THREAD

**Issue by Vortex265** [bigshortbets/bigshortbets-mobile#1]
Telefon Redmi Note Pro 8. Gdzie jest problem? Poniżej komunikat i historia metamask.

![Screenshot_2022-09-28-16-55-26-054_com bigshortbets mobile](https://user-images.githubusercontent.com/114598411/192816078-26cab581-fdfb-409c-8625-56fea647d116.jpg)

![Screenshot_2022-09-28-17-10-25-240_io metamask](https://user-images.githubusercontent.com/114598411/192816395-c811ba72-f597-422a-8695-1da8d7e435aa.jpg)

**Comment by Citral08** [comment]
Cześć, 

- upewni się że masz włączone autouzupełnianie haseł od google 
- jeżeli jesteś zalogowany na więcej niż kilka kont google na jednym urządzeniu to upewnij się że aplikacja nie trafiła do 'wykluczonych' na każdym z kont (ustawienia autozupełniania) 

bigshortbet$ Dev Team
